<a href="https://colab.research.google.com/github/SakshiGehani/J015_NLPassignments/blob/HomeWork/HW3_spaCy_Pipeline_J015_10_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a pipeline using spaCy

In [0]:
# Importing Pandas and spaCy modules
import pandas as pd
import spacy

In [2]:
## Reading 'json' type dataset into pandas dataframe
df = pd.read_json("http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz", lines=True)
df.head()

       reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 9 columns]

In [0]:
# loading the spaCy core English language model
sp = spacy.load('en_core_web_sm')

### For a single sentence/string

In [0]:
# Store the string as a simple spaCy document
sentence = sp(df.reviewText[0])     ## taking the first sentence of reviewText column as i/p str

In [5]:
# Tokenize the given string
for word in sentence:
    print(word.text)

I
bought
my
first
HP12C
in
about
1984
or
so
,
and
it
served
me
faithfully
until
2002
when
I
lost
it
while
travelling
.

I
searched
for
another
one
to
replace
it
,
but
found
one
difficult
to
come
by
in
my
area
.

So
,
I
decided
to
buy
up
and
purchased
an
HP
49G.

What
a
mistake
!

I
know
that
many
people
view
the
HP
49
G
(
now
49G+
)
as
the
flagship
of
the
HP
line
,
but
for
me
that
was
a
disaster
.
The
49
G
may
be
powerful
,
but
using
it
is
extremely
counterintuitive
...
and
the
manual
was
sketchy
at
best
.

The
12C
,
on
the
other
hand
,
does
what
I
need
in
a
way
that
makes
good
sense
to
me
.
If
you
are
looking
for
a
solid
,
reliable
calculator
,
the
HP12C
may
be
for
you
.

It
's
programmable
.

It
does
basic
statistics
well
,
and
many
business
applications
too
.

The
manual
makes
sense
;
you
will
be
up
and
running
in
short
order
.
I'm
ready
to
set
my
49
G
aside
and
move
back
to
my
old
friend
.

I
did
n't
even
have
to
replace
the
batteries
in
well
over
a
decade
of
use!HP
12C
,
I
'm
coming
home
!

In [6]:
# Assign Pos tags to the tokens in the given string
for word in sentence:
    print(word.text + '\t\t',  word.pos_)

I		 PRON
bought		 VERB
my		 DET
first		 ADJ
HP12C		 NOUN
in		 ADP
about		 ADV
1984		 NUM
or		 CCONJ
so		 ADV
,		 PUNCT
and		 CCONJ
it		 PRON
served		 VERB
me		 PRON
faithfully		 ADV
until		 ADP
2002		 NUM
when		 ADV
I		 PRON
lost		 VERB
it		 PRON
while		 ADP
travelling		 VERB
.		 PUNCT
 		 SPACE
I		 PRON
searched		 VERB
for		 ADP
another		 DET
one		 NOUN
to		 PART
replace		 VERB
it		 PRON
,		 PUNCT
but		 CCONJ
found		 VERB
one		 NUM
difficult		 ADJ
to		 PART
come		 VERB
by		 PART
in		 ADP
my		 DET
area		 NOUN
.		 PUNCT
 		 SPACE
So		 ADV
,		 PUNCT
I		 PRON
decided		 VERB
to		 PART
buy		 VERB
up		 PART
and		 CCONJ
purchased		 VERB
an		 DET
HP		 PROPN
49G.		 NUM
 		 SPACE
What		 DET
a		 DET
mistake		 NOUN
!		 PUNCT
 		 SPACE
I		 PRON
know		 VERB
that		 ADP
many		 ADJ
people		 NOUN
view		 VERB
the		 DET
HP		 PROPN
49		 NUM
G		 PROPN
(		 PUNCT
now		 ADV
49G+		 NUM
)		 PUNCT
as		 ADP
the		 DET
flagship		 NOUN
of		 ADP
the		 DET
HP		 PROPN
line		 NOUN
,		 PUNCT
but		 CCONJ
for		 ADP
me		 PRON
that		 DET
was		 VERB
a		 DET
disaster		 NOUN
.		 PUNCT
The		 DET
49		 NUM
G		 NOUN
may		 VERB
be		 VERB
powerful		 ADJ
,		 PUNCT
but		 CCONJ
using		 VERB
it		 PRON
is		 VERB
extremely		 ADV
counterintuitive		 ADJ
...		 PUNCT
and		 CCONJ
the		 DET
manual		 NOUN
was		 VERB
sketchy		 ADJ
at		 ADP
best		 ADJ
.		 PUNCT
 		 SPACE
The		 DET
12C		 NUM
,		 PUNCT
on		 ADP
the		 DET
other		 ADJ
hand		 NOUN
,		 PUNCT
does		 VERB
what		 PRON
I		 PRON
need		 VERB
in		 ADP
a		 DET
way		 NOUN
that		 DET
makes		 VERB
good		 ADJ
sense		 NOUN
to		 ADP
me		 PRON
.		 PUNCT
If		 ADP
you		 PRON
are		 VERB
looking		 VERB
for		 ADP
a		 DET
solid		 ADJ
,		 PUNCT
reliable		 ADJ
calculator		 NOUN
,		 PUNCT
the		 DET
HP12C		 NOUN
may		 VERB
be		 VERB
for		 ADP
you		 PRON
.		 PUNCT
 		 SPACE
It		 PRON
's		 VERB
programmable		 ADJ
.		 PUNCT
 		 SPACE
It		 PRON
does		 VERB
basic		 ADJ
statistics		 NOUN
well		 ADV
,		 PUNCT
and		 CCONJ
many		 ADJ
business		 NOUN
applications		 NOUN
too		 ADV
.		 PUNCT
 		 SPACE
The		 DET
manual		 NOUN
makes		 VERB
sense		 NOUN
;		 PUNCT
you		 PRON
will		 VERB
be		 VERB
up		 ADV
and		 CCONJ
running		 VERB
in		 ADP
short		 ADJ
order		 NOUN
.		 PUNCT
I'm		 PRON
ready		 ADJ
to		 PART
set		 VERB
my		 DET
49		 NUM
G		 NOUN
aside		 ADV
and		 CCONJ
move		 VERB
back		 ADV
to		 ADP
my		 DET
old		 ADJ
friend		 NOUN
.		 PUNCT
 		 SPACE
I		 PRON
did		 VERB
n't		 ADV
even		 ADV
have		 VERB
to		 PART
replace		 VERB
the		 DET
batteries		 NOUN
in		 ADP
well		 ADV
over		 ADP
a		 DET
decade		 NOUN
of		 ADP
use!HP		 ADJ
12C		 NUM
,		 PUNCT
I		 PRON
'm		 VERB
coming		 VERB
home		 ADV
!		 PUNCT

In [7]:
# Lemmatize the tokens in the given string
for word in sentence:
    print(word.text + '\t===>',  word.lemma_)

I	===> -PRON-
bought	===> buy
my	===> -PRON-
first	===> first
HP12C	===> hp12c
in	===> in
about	===> about
1984	===> 1984
or	===> or
so	===> so
,	===> ,
and	===> and
it	===> -PRON-
served	===> serve
me	===> -PRON-
faithfully	===> faithfully
until	===> until
2002	===> 2002
when	===> when
I	===> -PRON-
lost	===> lose
it	===> -PRON-
while	===> while
travelling	===> travel
.	===> .
 	===>
I	===> -PRON-
searched	===> search
for	===> for
another	===> another
one	===> one
to	===> to
replace	===> replace
it	===> -PRON-
,	===> ,
but	===> but
found	===> find
one	===> one
difficult	===> difficult
to	===> to
come	===> come
by	===> by
in	===> in
my	===> -PRON-
area	===> area
.	===> .
 	===>
So	===> so
,	===> ,
I	===> -PRON-
decided	===> decide
to	===> to
buy	===> buy
up	===> up
and	===> and
purchased	===> purchase
an	===> an
HP	===> HP
49G.	===> 49g.
 	===>
What	===> what
a	===> a
mistake	===> mistake
!	===> !
 	===>
I	===> -PRON-
know	===> know
that	===> that
many	===> many
people	===> people
view	===> view
the	===> the
HP	===> HP
49	===> 49
G	===> G
(	===> (
now	===> now
49G+	===> 49g+
)	===> )
as	===> as
the	===> the
flagship	===> flagship
of	===> of
the	===> the
HP	===> HP
line	===> line
,	===> ,
but	===> but
for	===> for
me	===> -PRON-
that	===> that
was	===> be
a	===> a
disaster	===> disaster
.	===> .
The	===> the
49	===> 49
G	===> g
may	===> may
be	===> be
powerful	===> powerful
,	===> ,
but	===> but
using	===> use
it	===> -PRON-
is	===> be
extremely	===> extremely
counterintuitive	===> counterintuitive
...	===> ...
and	===> and
the	===> the
manual	===> manual
was	===> be
sketchy	===> sketchy
at	===> at
best	===> good
.	===> .
 	===>
The	===> the
12C	===> 12c
,	===> ,
on	===> on
the	===> the
other	===> other
hand	===> hand
,	===> ,
does	===> do
what	===> what
I	===> -PRON-
need	===> need
in	===> in
a	===> a
way	===> way
that	===> that
makes	===> make
good	===> good
sense	===> sense
to	===> to
me	===> -PRON-
.	===> .
If	===> if
you	===> -PRON-
are	===> be
looking	===> look
for	===> for
a	===> a
solid	===> solid
,	===> ,
reliable	===> reliable
calculator	===> calculator
,	===> ,
the	===> the
HP12C	===> hp12c
may	===> may
be	===> be
for	===> for
you	===> -PRON-
.	===> .
 	===>
It	===> -PRON-
's	===> be
programmable	===> programmable
.	===> .
 	===>
It	===> -PRON-
does	===> do
basic	===> basic
statistics	===> statistic
well	===> well
,	===> ,
and	===> and
many	===> many
business	===> business
applications	===> application
too	===> too
.	===> .
 	===>
The	===> the
manual	===> manual
makes	===> make
sense	===> sense
;	===> ;
you	===> -PRON-
will	===> will
be	===> be
up	===> up
and	===> and
running	===> run
in	===> in
short	===> short
order	===> order
.	===> .
I'm	===> i'm
ready	===> ready
to	===> to
set	===> set
my	===> -PRON-
49	===> 49
G	===> g
aside	===> aside
and	===> and
move	===> move
back	===> back
to	===> to
my	===> -PRON-
old	===> old
friend	===> friend
.	===> .
 	===>
I	===> -PRON-
did	===> do
n't	===> not
even	===> even
have	===> have
to	===> to
replace	===> replace
the	===> the
batteries	===> battery
in	===> in
well	===> well
over	===> over
a	===> a
decade	===> decade
of	===> of
use!HP	===> use!hp
12C	===> 12c
,	===> ,
I	===> -PRON-
'm	===> be
coming	===> come
home	===> home
!	===> !

### For multiple strings (or entire column)

In [0]:
# Function to create a nlp pipeline using spaCy

def spacy_pipeline(str):
  pipe = dict()
  tokens = ' '.join([word.text for word in sp(str)])
  lemmatize = ' '.join([word.lemma_ for word in sp(str)])
  tagged = ' '.join([word.pos_ for word in sp(str)])

  pipe['Tokenize'] = tokens
  pipe['Lemmatize'] = lemmatize
  pipe['Pos_tag'] = tagged

  return pipe

In [0]:
## Function to find adjectives in the given string
def find_adj(str):
  adj = []
  
  for word in sp(str):
    if word.pos_ == 'ADJ':
      adj.append(word.text)

  return adj

In [0]:
## Function to find nouns in the given string
def find_noun(str):
  noun = []
  
  for word in sp(str):
    if word.pos_ == 'NOUN':
      noun.append(word.text)
      
  return noun

In [11]:
df1 = df.iloc[:100]     ## Taking only the first 100 rows of the dataset for input
spacy_pln = df1.reviewText.apply(spacy_pipeline)      ## Creating spaCy pipeline for all rows of ReviewText
df1.insert(5, 'Spacy Pipeline(Dict)_RevTxt', spacy_pln)
df1.head()

       reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 10 columns]

In [12]:
spacy_pln = df1.summary.apply(spacy_pipeline)
df1.insert(8, 'Spacy Pipeline(Dict)_Summary', spacy_pln)  ## Creating spaCy pipeline for all rows of Summary
df1.head()

       reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 11 columns]

In [13]:
adj_rev = df1.reviewText.apply(find_adj)   ## Finding adjectives in each row of ReviewText
df1.insert(6, 'Adjectives_RevTxt', adj_rev)
adj_summ = df1.summary.apply(find_adj)     ## Finding adjectives in each row of Summary
df1.insert(10, 'Adjectives_Summary', adj_summ)
df1.head()

       reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 13 columns]

In [14]:
noun_rev = df1.reviewText.apply(find_noun)      ## Finding nouns in each row of ReviewText
df1.insert(7, 'Nouns_RevTxt', noun_rev)
noun_summ = df1.summary.apply(find_noun)        ## Finding nouns in each row of Summary
df1.insert(12, 'Nouns_Summary', noun_summ)
df1.head()

       reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 15 columns]